import { build } from 'esbuild';
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const result = await build({
  entryPoints: ['src/server.mjs'], outfile: 'dist/server.mjs', bundle: true,
  platform: 'node', target: 'node22', format: 'esm', legalComments: 'eof',
  metafile: true,
  banner: { js: 'import { createRequire } from "node:module"; const require = createRequire(import.meta.url);' },
});

// Include the license texts of dependencies actually shipped in the runtime bundle.
const roots = new Set(Object.keys(result.metafile.inputs).flatMap((file) => {
  const match = file.match(/^(.*node_modules\/(?:@[^/]+\/)?[^/]+)\//);
  return match ? [match[1]] : [];
}));
const notices = ['# Bundled dependency notices\n\nGenerated by `npm run build`. These licenses apply to the bundled third-party packages.\n'];
for (const root of [...roots].sort()) {
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  const licenses = readdirSync(root).filter((name) => /^(licen[sc]e|copying|notice)(\.|$)/i.test(name));
  if (!licenses.length) throw new Error(`Missing dependency license: ${pkg.name}`);
  notices.push(`## ${pkg.name}@${pkg.version}\n`);
  for (const name of licenses.sort()) notices.push(readFileSync(join(root, name), 'utf8'));
}
writeFileSync('dist/THIRD_PARTY_NOTICES.md', notices.join('\n\n') + '\n');
